django-basics/learning_site/courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail, name='step'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

django-basics/learning_site/learning_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# . to import from current directory
from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', admin.site.urls),
    #r = raw string because these are regexes
    # ^$ = empty string
    url(r'^$', views.hello_world, name="home"),
]

urlpatterns += staticfiles_urlpatterns()

django-basics/learning_site/courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    #auto_now_add when a record is added its set to the timezone from settings
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title
        
class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    #blank true allows it to be optional
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.title

django-basics/learning_site/courses/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Course, Step

# Create your views here.
#def course_list(request):
#    courses = Course.objects.all()
#    output = ', '.join([str(course) for course in courses])
#    return HttpResponse(output)

def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})

def course_detail(request, pk):
    #course = Course.objects.get(pk=pk)
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
    #course = Course.objects.get(pk=pk)
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

django-basics/learning_site/learning_site/views.py
from django.http import HttpResponse
from django.shortcuts import render

def hello_world(request):
    return render(request, 'index.html')

django-basics/learning_site/courses/templates/courses/course_detail.html
{% extends "layout.html "%}

{% block title %}{{ course.title }}{%endblock%}

{% block content %}
    <article>
        <h2>{{ course.title }}</h2>
        <p>{{ course.description }}</p>
        <section>
            {% for step in course.step_set.all %}
                <h3><a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk  %}">{{ step.title }}</a></h3>
                <p>{{ step.description }}</p>
            {% endfor %}
        </section>
    </article>    
{%endblock%}

django-basics/learning_site/courses/templates/courses/course_list.html
{% extends "layout.html "%}

{% block title %}Course List{%endblock%}

{% block content %}
<div class="cards">
    {% for course in courses %}
        <div class="card">
            <h2><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></h2>
            <p class="card-copy">{{ course.description }}</p>
        </div>
    {% endfor %}
</div>
{%endblock%}

django-basics/learning_site/courses/templates/courses/step_detail.html
{% extends "layout.html "%}

{% block title %}{{ step.title }} - {{ step.course.title }}{%endblock%}

{% block content %}
    <article>
        <h2><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></h2>
        <h3>{{ step.title }}</h3>
        {{ step.content|linebreaks }}
    </article>    
{%endblock%}

django-basics/learning_site/templates/index.html
{% extends "layout.html "%}

{% block title %}Homepage{%endblock%}

{% block content %}
<h1>Welcome</h1>
{%endblock%}

django-basics/learning_site/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
</head>
<body>    
    <div class="site-container">
        <nav>
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'courses:list' %}">Courses</a>
        </nav>
        {% block content %}{% endblock %}
    </div>
</body>
</html>